# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VideoCreator' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VideoCreator

  pod 'Kingfisher', '~> 7.0'
  pod 'SnapKit', '~> 5.6.0'
  pod 'Moya', '~> 15.0'
  pod 'Nuke', '~> 10.7'

end
